domain: "<%= ENV['DOCKER_HOST_IP'] %>:3000"
secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
active_storage.service: local
amazon:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['AWS_DEFAULT_REGION'] %>
  bucket: <%= ENV['SHARETRIBE_BUCKET'] %>
