version: '2'
services:
  web:
    image: sharetribe/web
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_NAME: sharetribe
      DB_USER: sharetribe
      DB_PASSWORD: sharetribe
      DB_HOST: db
      SECRET_KEY_BASE: efb45049072749e140e75269195e43bcea254bd44ad8b53c53d12670a0e6e350ffb4eeb534a3f29e1755bf1a96c50fc113500449bc37bc34d938f79e83017cb4
      redis_host: redis
      AWS_ACCESS_KEY_ID: sharetribe
      AWS_SECRET_ACCESS_KEY: sharetribe
      AWS_DEFAULT_REGION: us-east-1
      SHARETRIBE_BUCKET: sharetribe
#  worker:
#    build: .
#    env_file: .env
#    environment:
#      - QUEUES=default,paperclip,mailers
#      - MAGICK_MAP_LIMIT=64MiB
#      - MAGICK_MEMORY_LIMIT=256MiB
#      - MAGICK_TIME_LIMIT=30
#    command: bundle exec rake jobs:work
  redis:
    image: redis:5.0.9-alpine
  db:
    image: mysql:5.7.29
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sharetribe
      MYSQL_USER: sharetribe
      MYSQL_PASSWORD: sharetribe
      MYSQL_ROOT_PASSWORD: 'Wipro@123'
#  s3:
#    image: minio/minio
#    ports:
#      - "9000:9000"
#    environment:
#      MINIO_ACCESS_KEY: sharetribe
#      MINIO_SECRET_KEY: sharetribe
#    command:
#      - minio
#      - server
#      - /data
#    volumes:
#      - s3-vol:/data
volumes:
  mysql-data:
    driver: local
#  s3-vol:
#    driver: local
networks:
  default:
    external:
      name: sharetribe
