version: '2'
services:
  web:
    image: sharetribe/web
    build: .
    ports:
      - "3000:3000"
      - "1080:1080"
    env_file:
      - ./web.env
#  worker:
#    image: sharetribe/web
#    volumes:
#      - image-vol:/opt/app/public/system
#    env_file:
#      - ./web.env
#    environment:
#      - QUEUES=default,paperclip,mailers
#      - MAGICK_MAP_LIMIT=64MiB
#      - MAGICK_MEMORY_LIMIT=256MiB
#      - MAGICK_TIME_LIMIT=30
#    command: bundle exec rake jobs:work
#  search:
#    image: sharetribe/web
##    command: '/bin/bash -l -c "bundle exec rake ts:configure ts:index; searchd --nodetach --pidfile --config config/development.sphinx.conf"'
#    command: 'bundle exec rake ts:configure ts:index; searchd --nodetach --pidfile --config config/development.sphinx.conf'
#    volumes:
#      - image-vol:/opt/app/public/system
#    env_file:
#      - ./web.env
#    environment:
#      SPHINX_HOST: ""
#    ports:
#      - "3563:3563"
  cache:
    image: redis:5.0.9-alpine
#  s3:
#    image: minio/minio
#    command: minio server /data
#    ports:
#      - "9000:9000"
#    volumes:
#      - s3-vol:/data
#    environment:
#      MINIO_ACCESS_KEY: sharetribe
#      MINIO_SECRET_KEY: sharetribe
  db:
    image: sharetribe/db
    build: ./db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sharetribe
      MYSQL_USER: sharetribe
      MYSQL_PASSWORD: sharetribe
      MYSQL_ROOT_PASSWORD: 'Wipro@123'
volumes:
  mysql-data:
    driver: local
  image-vol:
    driver: local
#  s3-vol:
#    driver: local
networks:
  default:
    external:
      name: sharetribe
